version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo/products:/data/db  # Ensure this path exists on the host
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Ensure this file exists
    networks:
      - spring_network

  mongo-express:
    image: mongo-express
    container_name: local-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb  # Connect mongo-express to the MongoDB container by name
    depends_on:
      - mongodb
    networks:
      - spring_network

volumes:
  mongodb:
    driver: local

networks:
  spring_network:
    driver: bridge
